"""
Django settings for salesplatform project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secrets from a local .env file (never commit this file — see .env.example)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or "django-insecure-&qyex*(l0#h(!zweg6m1mw23rlnyfd#g6zfpe7$@03oq!=5d0a"

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local dev; set DJANGO_DEBUG=False in your production .env
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

# Comma-separated list in production, e.g. ALLOWED_HOSTS=curex.example.com,www.curex.example.com
# The Curex Vercel domain is always allowed, while environment variables can add custom domains.
_default_allowed_hosts = [
    "localhost",
    "127.0.0.1",
    "testserver",
    "curex-diagnostic-center.vercel.app",
]
_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = _default_allowed_hosts + [
    h.strip() for h in _allowed_hosts_env.split(",")
    if h.strip() and h.strip() not in _default_allowed_hosts
]

# Trust HTTPS origins behind a proxy/load balancer (Vercel, Railway, Render, etc.) and let CSRF work
# for the Curex Vercel domain. Environment variables can add custom domains.
_default_csrf_origins = [
    "https://curex-diagnostic-center.vercel.app",
]
_csrf_origins_env = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = _default_csrf_origins + [
    o.strip() for o in _csrf_origins_env.split(",")
    if o.strip() and o.strip() not in _default_csrf_origins
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'widget_tweaks',

    'accounts',
    'inventory',
    'sales',
    'customers',
    'orders',
    'dashboard',
    'whatsapp_bot',
    'results',
    'sitecontent',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'salesplatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'salesplatform.context_processors.business_identity',
            ],
        },
    },
]

WSGI_APPLICATION = 'salesplatform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG else
            "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Optional S3-compatible storage for uploaded media (patient results, product images) ---
# IMPORTANT for Render/Railway/Heroku-style hosts: their local disk is wiped on every deploy
# and restart. Uploaded test results would be silently lost without this. Works with AWS S3,
# Cloudflare R2, Backblaze B2, or DigitalOcean Spaces — anything S3-API compatible.
# Leave USE_S3 unset/false to keep using local disk storage (fine for local dev only).
USE_S3 = os.environ.get("USE_S3", "False").lower() in ("1", "true", "yes")

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL")  # e.g. https://<accountid>.r2.cloudflarestorage.com
    AWS_S3_CUSTOM_DOMAIN = os.environ.get("AWS_S3_CUSTOM_DOMAIN")  # optional CDN/custom domain
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = True  # signed URLs — appropriate since results contain patient data
    AWS_QUERYSTRING_EXPIRE = 3600  # signed link expires in 1 hour

    STORAGES["default"] = {"BACKEND": "storages.backends.s3.S3Storage"}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'accounts:login'

# --- Business / site settings ---
SITE_NAME = "Curex Diagnostic Center"
SITE_MOTTO = "ACCURATE RESULT, COMPASSIONATE CARE."
SITE_ADDRESS = "Adeleke University Road, Isale Ilori, Close to Olabebo, Ede, Osun State"
SITE_PHONE = "09122997406"
SITE_EMAIL = "curex.diagcenter@gmail.com"
WHATSAPP_BUSINESS_NUMBER = "2349122997406"  # international format, no + or spaces
LOW_STOCK_DEFAULT_THRESHOLD = 5
EXPIRY_WARNING_DAYS = 30

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- WhatsApp Cloud API (auto-reply bot) ---
# Get these from developers.facebook.com -> your app -> WhatsApp -> API Setup
# Set the real values in a local .env file (see .env.example) — never hardcode them here.
# WhatsApp booking mode
# "assisted" uses the WhatsApp app / WhatsApp Web via wa.me links and does not
# require a Meta developer app, webhook, Cloud API token, or Phone Number ID.
WHATSAPP_MODE = os.environ.get("WHATSAPP_MODE", "assisted").strip().lower()
WHATSAPP_ASSISTED_MODE = WHATSAPP_MODE == "assisted"
WHATSAPP_BOT_ENABLED = WHATSAPP_ASSISTED_MODE or os.environ.get("WHATSAPP_BOT_ENABLED", "True").lower() in ("1", "true", "yes", "on")

# These values are optional and only used if the project is intentionally switched
# to Meta Cloud API mode in the future. Assisted mode does not depend on them.
WHATSAPP_CLOUD_API_TOKEN = os.environ.get("WHATSAPP_CLOUD_API_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.environ.get("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_VERIFY_TOKEN = os.environ.get("WHATSAPP_VERIFY_TOKEN", "")
WHATSAPP_API_VERSION = os.environ.get("WHATSAPP_API_VERSION", "v20.0")
BUSINESS_HOURS = "Monday - Saturday, 8:00 AM - 6:00 PM"
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "https://yourdomain.com")  # no trailing slash

# Optional — leave blank to hide the icon on the site. Fill in with real profile URLs.
SITE_FACEBOOK = os.environ.get("SITE_FACEBOOK", "")
SITE_INSTAGRAM = os.environ.get("SITE_INSTAGRAM", "")
SITE_TWITTER = os.environ.get("SITE_TWITTER", "")

# --- AI-powered replies for open-ended questions the menu doesn't cover ---
# Optional: if unset, the bot falls back to a canned "didn't understand" reply instead.
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")

# --- Staff notifications (new appointments, human-handoff requests) ---
# Comma-separated list of email addresses, e.g. "front-desk@curex.com,manager@curex.com"
STAFF_NOTIFICATION_EMAILS = [
    e.strip() for e in os.environ.get("STAFF_NOTIFICATION_EMAILS", "").split(",") if e.strip()
]
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", SITE_EMAIL)
