"""
Django settings for salesplatform project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url


# =============================================================================
# BASE DIRECTORY / ENVIRONMENT
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Load local .env file.
# Vercel environment variables take precedence because load_dotenv()
# does not override variables that already exist in the environment.
load_dotenv(BASE_DIR / ".env")


# =============================================================================
# SECURITY
# =============================================================================

# Detect Vercel.
IS_VERCEL = os.environ.get("VERCEL", "").lower() in (
    "1",
    "true",
    "yes",
    "on",
)

# Secret key.
#
# IMPORTANT:
# Set DJANGO_SECRET_KEY in Vercel Environment Variables.
#
# For local development, a development fallback is provided so that the
# project does not immediately crash if .env has not been configured.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if IS_VERCEL:
        raise RuntimeError(
            "DJANGO_SECRET_KEY is required in Vercel Environment Variables."
        )

    SECRET_KEY = "dev-only-curex-secret-key-change-this"


# Debug should be OFF unless explicitly enabled.
DEBUG = os.environ.get(
    "DJANGO_DEBUG",
    "False",
).lower() in (
    "1",
    "true",
    "yes",
    "on",
)


# =============================================================================
# ALLOWED HOSTS
# =============================================================================

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "testserver",
    "curex-diagnostic-center.vercel.app",
]

# Allow additional hosts supplied through environment variables.
extra_allowed_hosts = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "",
).split(",")

for host in extra_allowed_hosts:
    host = host.strip()

    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)


# Vercel generates preview domains such as:
# curex-diagnostic-center-hk4pjgatc-babsbooks.vercel.app
#
# ".vercel.app" allows those Vercel subdomains.
if IS_VERCEL and ".vercel.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".vercel.app")


# =============================================================================
# CSRF / HTTPS
# =============================================================================

CSRF_TRUSTED_ORIGINS = [
    "https://curex-diagnostic-center.vercel.app",
]

# Allow Vercel preview URLs.
if IS_VERCEL:
    CSRF_TRUSTED_ORIGINS.append("https://*.vercel.app")


# Add custom trusted origins from environment variables.
extra_csrf_origins = os.environ.get(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "",
).split(",")

for origin in extra_csrf_origins:
    origin = origin.strip()

    if origin and origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)


# Vercel sits behind a proxy and forwards the original protocol.
SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    "widget_tweaks",

    # Project apps
    "accounts",
    "inventory",
    "sales",
    "customers",
    "orders",
    "dashboard",
    "whatsapp_bot",
    "results",
    "sitecontent",
]


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise serves static files in production.
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =============================================================================
# URL / WSGI
# =============================================================================

ROOT_URLCONF = "salesplatform.urls"

WSGI_APPLICATION = "salesplatform.wsgi.application"


# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "salesplatform.context_processors.business_identity",
            ],
        },
    },
]


# =============================================================================
# DATABASE
# =============================================================================

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",

        # Keep database connections alive where supported.
        conn_max_age=600,

        # Check connections before using them.
        conn_health_checks=True,
    )
}


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# =============================================================================
# MEDIA FILES / STORAGE
# =============================================================================
#
# IMPORTANT:
#
# Vercel's filesystem is READ-ONLY.
#
# Therefore:
#
# Local development:
#     USE_S3=False
#     -> files use local media/
#
# Vercel:
#     USE_S3=True
#     -> files use Supabase S3 Storage
#
# This includes:
# - patient result uploads
# - product images
# - any other Django FileField/ImageField uploads
# =============================================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# Read USE_S3 from environment.
USE_S3 = os.environ.get(
    "USE_S3",
    "False",
).lower() in (
    "1",
    "true",
    "yes",
    "on",
)


# Vercel MUST always use S3/object storage.
if IS_VERCEL:
    USE_S3 = True


# =============================================================================
# DJANGO STORAGE BACKENDS
# =============================================================================

STORAGES = {
    # Default local storage.
    #
    # This gets replaced with S3Storage when USE_S3=True.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    # Static files.
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else
            "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}


# =============================================================================
# SUPABASE S3 STORAGE
# =============================================================================

if USE_S3:

    # -------------------------------------------------------------------------
    # Supabase S3 credentials
    # -------------------------------------------------------------------------
    #
    # NEVER put the actual credentials here.
    #
    # These are ENVIRONMENT VARIABLE NAMES.
    #
    AWS_ACCESS_KEY_ID = os.environ.get(
        "AWS_ACCESS_KEY_ID",
        "",
    )

    AWS_SECRET_ACCESS_KEY = os.environ.get(
        "AWS_SECRET_ACCESS_KEY",
        "",
    )

    AWS_STORAGE_BUCKET_NAME = os.environ.get(
        "AWS_STORAGE_BUCKET_NAME",
        "curexdiagnostic",
    )

    AWS_S3_REGION_NAME = os.environ.get(
        "AWS_S3_REGION_NAME",
        "eu-central-1",
    )

    AWS_S3_ENDPOINT_URL = os.environ.get(
        "AWS_S3_ENDPOINT_URL",
        "https://elcdmtupofucgjzabuxc.storage.supabase.co/storage/v1/s3",
    )

    AWS_S3_ADDRESSING_STYLE = os.environ.get(
        "AWS_S3_ADDRESSING_STYLE",
        "path",
    )

    AWS_S3_SIGNATURE_VERSION = "s3v4"

    # Do not use legacy ACLs.
    AWS_DEFAULT_ACL = None

    # Prevent accidental overwriting of files with the same name.
    AWS_S3_FILE_OVERWRITE = False

    # Generate signed URLs for private objects.
    AWS_QUERYSTRING_AUTH = True

    # Signed URL lifetime: 1 hour.
    AWS_QUERYSTRING_EXPIRE = 3600

    # Use django-storages S3 backend.
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
    }


# =============================================================================
# DEFAULT MODEL FIELD
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# LOGIN / AUTHENTICATION
# =============================================================================

LOGIN_URL = "accounts:login"

LOGIN_REDIRECT_URL = "dashboard:home"

LOGOUT_REDIRECT_URL = "accounts:login"


# =============================================================================
# BUSINESS / SITE SETTINGS
# =============================================================================

SITE_NAME = "Curex Diagnostic Center"

SITE_MOTTO = "ACCURATE RESULT, COMPASSIONATE CARE."

SITE_ADDRESS = (
    "Adeleke University Road, Isale Ilori, "
    "Close to Olabebo, Ede, Osun State"
)

SITE_PHONE = "09122997406"

SITE_EMAIL = "curex.diagcenter@gmail.com"

WHATSAPP_BUSINESS_NUMBER = "2349122997406"

LOW_STOCK_DEFAULT_THRESHOLD = 5

EXPIRY_WARNING_DAYS = 30


# =============================================================================
# EMAIL
# =============================================================================
#
# Console email is useful for local development.
#
# If you later want real production emails, configure SMTP environment
# variables and change EMAIL_BACKEND.
# =============================================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)


# =============================================================================
# WHATSAPP
# =============================================================================

# "assisted" mode uses:
# - WhatsApp links
# - WhatsApp Web
# - wa.me
#
# It does NOT require Meta Cloud API.

WHATSAPP_MODE = os.environ.get(
    "WHATSAPP_MODE",
    "assisted",
).strip().lower()

WHATSAPP_ASSISTED_MODE = (
    WHATSAPP_MODE == "assisted"
)


WHATSAPP_BOT_ENABLED = (
    WHATSAPP_ASSISTED_MODE
    or
    os.environ.get(
        "WHATSAPP_BOT_ENABLED",
        "True",
    ).lower()
    in (
        "1",
        "true",
        "yes",
        "on",
    )
)


# =============================================================================
# OPTIONAL WHATSAPP CLOUD API SETTINGS
# =============================================================================
#
# These are only required if you intentionally switch to Meta Cloud API mode.
# Assisted mode does not use them.
# =============================================================================

WHATSAPP_CLOUD_API_TOKEN = os.environ.get(
    "WHATSAPP_CLOUD_API_TOKEN",
    "",
)

WHATSAPP_PHONE_NUMBER_ID = os.environ.get(
    "WHATSAPP_PHONE_NUMBER_ID",
    "",
)

WHATSAPP_VERIFY_TOKEN = os.environ.get(
    "WHATSAPP_VERIFY_TOKEN",
    "",
)

WHATSAPP_API_VERSION = os.environ.get(
    "WHATSAPP_API_VERSION",
    "v20.0",
)


# =============================================================================
# BUSINESS HOURS
# =============================================================================

BUSINESS_HOURS = (
    "Monday - Saturday, 8:00 AM - 6:00 PM"
)


# =============================================================================
# SITE BASE URL
# =============================================================================

SITE_BASE_URL = os.environ.get(
    "SITE_BASE_URL",
    "https://curex-diagnostic-center.vercel.app",
).rstrip("/")


# =============================================================================
# SOCIAL MEDIA
# =============================================================================

SITE_FACEBOOK = os.environ.get(
    "SITE_FACEBOOK",
    "",
)

SITE_INSTAGRAM = os.environ.get(
    "SITE_INSTAGRAM",
    "",
)

SITE_TWITTER = os.environ.get(
    "SITE_TWITTER",
    "",
)


# =============================================================================
# ANTHROPIC AI
# =============================================================================

ANTHROPIC_API_KEY = os.environ.get(
    "ANTHROPIC_API_KEY",
    "",
)

ANTHROPIC_MODEL = os.environ.get(
    "ANTHROPIC_MODEL",
    "claude-sonnet-4-6",
)


# =============================================================================
# STAFF NOTIFICATIONS
# =============================================================================

# Comma-separated list:
#
# STAFF_NOTIFICATION_EMAILS=
# front-desk@example.com,manager@example.com
#
# Empty by default.

STAFF_NOTIFICATION_EMAILS = [
    email.strip()
    for email in os.environ.get(
        "STAFF_NOTIFICATION_EMAILS",
        "",
    ).split(",")
    if email.strip()
]


# =============================================================================
# DEFAULT EMAIL ADDRESS
# =============================================================================

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    SITE_EMAIL,
)