# Generated by Django 6.0.7 on 2026-08-06 12:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('equipment_type', models.CharField(blank=True, help_text='e.g. Haematology Analyzer, Ultrasound Scanner', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment_photos/')),
                ('location', models.CharField(blank=True, help_text='e.g. Lab Room 1, Scan Room', max_length=150)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('needs_maintenance', 'Needs Maintenance'), ('under_repair', 'Under Repair'), ('offline', 'Offline')], default='operational', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('last_serviced_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField()),
                ('status_after', models.CharField(choices=[('operational', 'Operational'), ('needs_maintenance', 'Needs Maintenance'), ('under_repair', 'Under Repair'), ('offline', 'Offline')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='equipment.equipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date', '-created_at'],
            },
        ),
    ]
