# Generated by Django 6.0.7 on 2026-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Lab Manager'), ('cashier', 'Front Desk / Receptionist'), ('lab_tech', 'Lab Technician / Phlebotomist'), ('delivery', 'Sample Collection Rider')], default='cashier', max_length=20),
        ),
    ]
