# Generated by Django 6.0.7 on 2026-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='public_bio',
            field=models.TextField(blank=True, help_text='Short public bio/qualifications shown on the website'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='public_title',
            field=models.CharField(blank=True, help_text="e.g. 'Consultant Pathologist' — shown publicly instead of the internal role", max_length=150),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='show_on_website',
            field=models.BooleanField(default=False, help_text="Show this staff member on the public 'Our Specialists' section"),
        ),
    ]
