# Generated by Django 6.0.7 on 2026-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Test details, sample type required, turnaround time, etc.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Reagent/kit expiry date. Leave blank for services with no physical expiry.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="e.g. 'Full Blood Count', 'Abdominal Ultrasound', or 'Malaria RDT Kit'", max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Price charged to the patient', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, unique=True, verbose_name='Test/Item Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='For tests: available test slots/kits. For reagents: units in stock.'),
        ),
    ]
