# Generated by Django 6.0.7 on 2026-07-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(max_length=32, unique=True, verbose_name='WhatsApp ID / Phone')),
                ('profile_name', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(choices=[('new', 'New'), ('menu', 'At Main Menu'), ('awaiting_test_query', 'Awaiting Test Name'), ('needs_human', 'Needs Human Follow-up')], default='new', max_length=32)),
                ('needs_human', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('linked_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to='customers.customer')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing (bot)')], max_length=8)),
                ('body', models.TextField()),
                ('wa_message_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_bot.whatsappcontact')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
