# Generated by Django 6.0.7 on 2026-07-29 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_description_alter_product_expiry_date_and_more'),
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='pending_date_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='pending_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('menu', 'At Main Menu'), ('awaiting_test_query', 'Awaiting Test Name'), ('awaiting_availability_query', 'Awaiting Availability Query'), ('booking_select_test', 'Booking: Choosing Test'), ('booking_select_date', 'Booking: Choosing Date'), ('booking_confirm', 'Booking: Awaiting Confirmation'), ('needs_human', 'Needs Human Follow-up')], default='new', max_length=32),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date_text', models.CharField(help_text='Free-text date/time the patient asked for', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Staff Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='whatsapp_bot.whatsappcontact')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
