# Generated by Django 6.0.7 on 2026-08-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_whatsappcontact_pending_date_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontact',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('menu', 'At Main Menu'), ('awaiting_test_query', 'Awaiting Test Name'), ('awaiting_availability_query', 'Awaiting Availability Query'), ('awaiting_symptom_description', 'Awaiting Symptom Description'), ('booking_select_test', 'Booking: Choosing Test'), ('booking_select_date', 'Booking: Choosing Date'), ('booking_confirm', 'Booking: Awaiting Confirmation'), ('needs_human', 'Needs Human Follow-up')], default='new', max_length=32),
        ),
    ]
