# Generated by Django 6.0.7 on 2026-09-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0003_alter_whatsappcontact_state"),
        ("whatsapp_bot", "0004_sales_workspace_fields"),
    ]

    operations = []
