# Generated by Django 6.0.7 on 2026-07-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='whatsapp_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='orders.whatsapporder'),
        ),
        migrations.AddField(
            model_name='whatsapporderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.whatsapporder'),
        ),
        migrations.AddField(
            model_name='whatsapporderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_order_items', to='inventory.product'),
        ),
    ]
